apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
  namespace: atividade-kubernetes
spec:
  containers:
  - name: nginx
    image: nginx    
    ports:
      - containerPort: 80