apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
  namespace: atividade-kubernetes
spec:
  containers:
  - name: mysql
    image: mysql:8.0    
    ports:
      - containerPort: 3306